#:import kivy kivy

<TimerLayout>:
	orientation: 'vertical'
	Label:
	    color: (0, 1, 0, 1)
		text: root.timerText
		font_size: self.height * 0.5
	Button:
		text: root.buttonText
		font_size: self.height * 0.3
		on_release: root.toggle()
	BoxLayout:
	    orientation: 'horizontal'
	    TextInput:
	        id: setting
	    Button:
	        text: 'Set'
	        on_release:
	            root.set_time(setting.text)
	            setting.text = ''
